apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikigai
  labels:
    app: ikigai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikigai
  template:
    metadata:
      labels:
        app: ikigai
    spec:
      containers:
        - name: ikigai
          image: 646390474080.dkr.ecr.eu-west-1.amazonaws.com/ikigai:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"